### ISSUE TITLE
graphical updates to dashboard - 1

### ISSUE THREAD

**Issue by ayalcin1995** [dmsfabiano/dashboard#1]
I will start posting some updates here.

on the user_dashboard pages the search capability and list should be after the graphs

**Comment by dmsfabiano** [comment]
What do you mean by the search capability and list?  The search feature is only available in the table, as we can look up strings and do querys every time; this method is effective for the table. Mainly because every input is basically 'queryble'. However, adding a search feature within the graph is a little more challenging. I do not even think flot supports that. This is why I added the search by date feature, it works really fast and it has basic times that are useful like 'today', 'yesterday', 'last 7 days', and you can also do any custom time. Because after all the graphs were meant for an analysis over time, rather than specific; but I added the calendar to have a little of both worlds.  Let me know.

**Comment by ayalcin1995** [comment]
what i mean is move the table to below the graphs. it is just positioning issue. no changes to either the table or the graphs

**Comment by dmsfabiano** [comment]
Okay, will do.
